//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Backend.Models
{
    using Newtonsoft.Json;
    using System;
    using System.Collections.Generic;
    
    public partial class EnvioMaritimo
    {
        public string numeroGuia { get; set; }
        public string documentoCliente { get; set; }
        public Nullable<int> idTipoProducto { get; set; }
        public Nullable<int> cantidad { get; set; }
        public Nullable<System.DateTime> fechaRegistro { get; set; }
        public Nullable<System.DateTime> fechaEntrega { get; set; }
        public Nullable<int> idPuerto { get; set; }
        public string numeroFlota { get; set; }
        public Nullable<decimal> precioEnvio { get; set; }
        public Nullable<decimal> descuento { get; set; }
        public Nullable<decimal> valorTotal { get; set; }

        [JsonIgnore]
        public virtual Cliente Cliente { get; set; }
        [JsonIgnore]
        public virtual Flota Flota { get; set; }
        [JsonIgnore]
        public virtual Puerto Puerto { get; set; }
        [JsonIgnore]
        public virtual TipoProducto TipoProducto { get; set; }
    }
}
