//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Backend.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class LogisticaEntities : DbContext
    {
        public LogisticaEntities()
            : base("name=LogisticaEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Bodega> Bodegas { get; set; }
        public virtual DbSet<Cliente> Clientes { get; set; }
        public virtual DbSet<EnvioMaritimo> EnvioMaritimoes { get; set; }
        public virtual DbSet<EnvioTerrestre> EnvioTerrestres { get; set; }
        public virtual DbSet<Flota> Flotas { get; set; }
        public virtual DbSet<Puerto> Puertoes { get; set; }
        public virtual DbSet<sysdiagram> sysdiagrams { get; set; }
        public virtual DbSet<TipoProducto> TipoProductoes { get; set; }
        public virtual DbSet<Vehiculo> Vehiculoes { get; set; }
    }
}
